### ISSUE TITLE
Bug - check_results_dir does not work if it's symlinked

### ISSUE THREAD

**Issue by ssaxnagios** [NagiosEnterprises/nrdp#13]
When having the check_results_dir point to a path that contains a symlink, PHP's file_exist function doesn't work properly:

http://php.net/manual/en/function.file-exists.php#73904

You can validate like so:

```
mkdir /testing
mv /usr/local/nagios/var/spool /testing/
ln -s /testing/spool /usr/local/nagios/var/spool
chown -h nagios.nagios /usr/local/nagios/var/spool
chown nagios.nagios /testing
chmod 775 /testing
```

Then go to http://YOURSERVER/nrdp/ and submit a check result and you will receive:

`<result><status>-1</status><message>BAD CHECK RESULTS DIR</message></result>`

**Comment by hedenface** [comment]
I bet the function works fine (they usually do), but whatever we're doing with it fudges something.

**Comment by hedenface** [comment]
Fixed in https://github.com/NagiosEnterprises/nrdp/commit/f7c2764d2625b163b1c111f9301d7f2b7ed2876b.
