### ISSUE TITLE
send_nrdp.php - Help does not explain how to use STDIN or change the delimiter

### ISSUE THREAD

**Issue by box293** [NagiosEnterprises/nrdp#17]
Looking at the script I can pipe to `send_nrdp.php` with the following:
```
printf "centos01\t0\tThe host is up and OK\n" | ./send_nrdp.php --url=http://10.25.5.2/nrdp --token=XXXXX --usestdin
```

`--usestdin` is not explained in the help. It also appears that changing the delimiter is not an option.

**Comment by hedenface** [comment]
Added in https://github.com/NagiosEnterprises/nrdp/commit/49edaa3001077ce3f75278c1dcaea34553c357d2
