### ISSUE TITLE
External Command Permissions

### ISSUE THREAD

**Issue by box293** [NagiosEnterprises/nrdp#25]
It would be useful if you could define granular permissions for the external commands. For example I want to allow a token to `ACKNOWLEDGE_HOST_PROBLEM` and `ACKNOWLEDGE_SVC_PROBLEM` however I don't want it to be able to `DISABLE_HOST_CHECK`, `DISABLE_HOST_SVC_CHECKS`, `DISABLE_PASSIVE_HOST_CHECKS`, `DISABLE_PASSIVE_SVC_CHECKS`.

I understand that connection to NRDP can be something other than a token, whatever authentication method used would have these permissions used.

**Comment by hedenface** [comment]
Fixed in https://github.com/NagiosEnterprises/nrdp/commit/f7c2764d2625b163b1c111f9301d7f2b7ed2876b

**Comment by hedenface** [comment]
I had two issues open at once. That commit was actually the fix for #13.

**Comment by hedenface** [comment]
Added in https://github.com/NagiosEnterprises/nrdp/commit/0525b8d55a92cdd7181c1b439a32bf740bb1d7b7
