### ISSUE TITLE
[RFE]  Adding debugging sensor lines into nrdp server code

### ISSUE THREAD

**Issue by tjyang** [NagiosEnterprises/nrdp#27]
Hi

I am hoping one can turn on debug flag in nrdp config file and the flow of receiving xml data from nrdp client, from httpd and writing commands to nagios server activities be logged into a file. 

This will help greatly when nrdp server is not working.

**Comment by hedenface** [comment]
Added in https://github.com/NagiosEnterprises/nrdp/commit/f206988ebd9a54dcac37b20761f12d7b0b21ea06.

**Comment by tjyang** [comment]
@hedenface. 
Thanks for adding the debug lines.
