### ISSUE TITLE
XML Check Result and JSON Check Result do not work in 1.5.0

### ISSUE THREAD

**Issue by douglasawh** [NagiosEnterprises/nrdp#28]
CentOS 7, Core 4.3.4. "Submit Nagios Command" does work.

**Comment by douglasawh** [comment]
yum -y install php-process seems to resolve the output, but the state still does not change.

**Comment by douglasawh** [comment]
turns out it just does not handle bad states. If you put a host state that is not 0-2 the UI will keep the previous state. The new state shows up "properly" in the nagios.log

`[1513970927] PASSIVE HOST CHECK: localhost;10;hahah`

The php-process installation should be added to the instructions, at least for CentOS 7.

**Comment by hedenface** [comment]
Fixed in https://github.com/NagiosEnterprises/nrdp/commit/9967a5f66a78af7c1284a52e55b0f375a240862e

**Comment by hedenface** [comment]
Also, an FYI - the allowing of passing an integer in outside of the normal scope is handled by Core, and as such should be left for that.
