### ISSUE TITLE
Permit additional cmd=submitcheck handler plugins

### ISSUE THREAD

**Issue by dm0-** [NagiosEnterprises/nrdp#3]
I wrote a plugin to duplicate checkresults requests to backup NRDP servers, but found the plugin callback gets registered after the nagioscorepassivecheck plugin which calls exit().  I could rename it so the plugins' alphabetical sorting takes care of this issue, but I'd rather have a more general fix if possible.

Maybe the nagioscore plugins can remove their `exit()` calls and [the missing handler warning](/NagiosEnterprises/nrdp/blob/master/server/index.php#L57) can be prefixed with `if (!headers_sent())`?

Or maybe a new `CALLBACK_PREPROCESS_REQUEST` could be added for calling plugin functions that don't write output or exit?

Or maybe add an option to `register_callback()` that prepends functions instead of appending?

What do you think?

**Comment by tmcnag** [comment]
Maybe a naïve implementation, but the above commit I made seems to fix this.  I took the prepend approach, so you can now register like so:

`register_callback(CALLBACK_PROCESS_REQUEST,'zcustomplugin_process_request', 1);`

To prepend to the callback queue.

**Comment by jomann09** [comment]
Merged in #4
