### ISSUE TITLE
nrdp license is *not*  OSI-approved

### ISSUE THREAD

**Issue by omadjoudj** [NagiosEnterprises/nrdp#32]
Hello

In order to package nrdp in Fedora and EPEL (Extra Packages for Enterprise Linux), the software must be licensed under an OSI-approved FLOSS license.

Is there a possibility to do so ? it seems that NOSL is no approved [1]

[1] https://github.com/spdx/license-list-data/blob/master/licenses.md

**Comment by hedenface** [comment]
The NOSL listed there is not the same thing as the Nagios Open Source License, I believe.

**Comment by athmane** [comment]
Sorry for confusion, I'm referring to Nagios Open Source License [1], more precisely point N/3 (forking) and N/6 (usage restrictions), it was raised when I submitted nrdp package for review [2]

[1] https://github.com/NagiosEnterprises/nrdp/blob/master/LICENSE.rst
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1284132

**Comment by hedenface** [comment]
The Nagios Open Source License was born during a time where it served a rather helpful purpose.

I'll see what I can do :)

There are various other projects that we develop that use the Nagios Open Source License, and I'll see what I can do about those as well.

**Comment by hedenface** [comment]
We're actually in the process of migrating to the GPL for this project. I just haven't had the time to work on it - I did receive approval, though.

**Comment by BenoitPoulet** [comment]
Any update ?

**Comment by hedenface** [comment]
No update as of now, no.

**Comment by xavierba** [comment]
Any update on a GPL licenced release ?

**Comment by jomann09** [comment]
This is set to be updated for version 2, I will take a look at this and see if we can't get a release out soon.

**Comment by jomann09** [comment]
Closing this now that 2.0.0 is out and the license has been changed to GPLv3.
