### ISSUE TITLE
NRDP JSONDATA check doesn't works and get message as "NO DATA"

### ISSUE THREAD

**Issue by manish2479** [NagiosEnterprises/nrdp#39]
Hi 

I trying to use the NRDP check using the JSONDATA and it's not working and gives message as "NO DATA", while XMLDATA works fine.

Here are my commands and error 

JSONDATA test
```
curl -f -d 'token=TOKEN&cmd=submitcheck&JSONDATA={ "checkresults": [ { "checkresult": { "type": "service", "checktype": "1", }, "hostname": "node2", "servicename": "Cron_Err", "state": "1", "output": "Cron_Err in Warning state", } ] }'  http://nagios.domain.com/nrdp/
<?xml version="1.0" encoding="utf-8"?>
<result>
  <status>-1</status>
  <message>NO DATA</message>
</result>
```

XMLDATA test
```
curl -f -d "token=TOKEN&cmd=submitcheck&XMLDATA=<?xml version='1.0'?><checkresults><checkresult type='service' checktype='1'><hostname>node2</hostname> <servicename>Cron_Err</servicename><state>1</state><output>Cron_Err in Warning state</output></checkresult></checkresults>" http://nagios.domain.com/nrdp/
<?xml version="1.0" encoding="utf-8"?>
<result>
  <status>1</status>
  <message>OK</message>
    <meta>
       <output>1 checks processed.</output>
    </meta>
</result>
```

So is there I am missing anything in the JSONDATA command syntax. 

Thank You,

**Comment by jomann09** [comment]
It looks like your example JSON is not valid (you can copy/paste it into a JSON validation site online)

This should be a valid version of the above:
```
{
  "checkresults": [
    {
      "checkresult": {
        "type": "service",
        "checktype": "1"
      },
      "hostname": "node2",
      "servicename": "Cron_Err",
      "state": "1",
      "output": "Cron_Err in Warning state"
    }
  ]
}
```

**Comment by manish2479** [comment]
Hi Jake,

Thank you for prompt response, I have used same JSON syntax but some how it got changed and placed double quotes in different format here, when I created it in bug report. I have fixed those quotes in my original post. But here is one more test.

```
curl -f -d 'token=TOKEN&cmd=submitcheck&JSONDATA={ "checkresults": [{ "checkresult": { "type": "service", "checktype": "1" }, "hostname": "node2", "servicename": "Cron_Err", "state": "1", "output": "Cron_Err in Warning state" }]}' http://nagios.domain.com/nrdp/
<?xml version="1.0" encoding="utf-8"?>
<result>
  <status>-1</status>
  <message>NO DATA</message>
</result>
```

**Comment by jomann09** [comment]
What are you running this on? What version of NRDP?

**Comment by jomann09** [comment]
You have to be on version 1.5+ to be able to use the JSONDATA option

**Comment by manish2479** [comment]
Hi Jake,

Thank you, after doing an upgrade of NRDP version to 1.5 it worked fine. I appreciate your help.

Thank You,

**Comment by jomann09** [comment]
No problem, glad this was resolved!

**Comment by manish2479** [comment]
Hi Jake,

Not sure if I should open a new ticket or ask it here. But I would like to know how I can use this with webhook in body section which takes care of token and cmd section.

`'token=TOKEN&cmd=submitcheck&JSONDATA={ "checkresults": [{ "checkresult": { "type": "service", "checktype": "1" }, "hostname": "node2", "servicename": "Cron_Err", "state": "1", "output": "Cron_Err in Warning state" }]}'`

Thank you
