### ISSUE TITLE
NRDP on XI: semicolon changes to colon

### ISSUE THREAD

**Issue by jvandermeulen** [NagiosEnterprises/nrdp#40]
Passing check results toward NRDP containing one or multiple semicolon characters in status information field results in **semicolon** to **colon** translation as output.

Problem is easily reproducible, just set set send_nrdp.sh  `-s` parameter to something like ` OK: result1=1; result2=2;​`

![nrdp_bug](https://user-images.githubusercontent.com/838001/52512920-bb489480-2c07-11e9-9914-afca28f3201b.png)

**Comment by jomann09** [comment]
I fixed a weird issue where `check_nrdp.sh` was sending XML that for some reason the php reciever couldn't get but the issue with the `;` turning into `:` seems to be on the Nagios Core side so I am going to open an issue there. It is writing the appropriate output into the `/usr/local/nagios/var/spool/checkresults` directory.

Running this command:
```
./send_nrdp.sh -u https://localhost/nrdp/ -t test -H localhost -s PING -S 2 -o 'OK: result1=1; result2=2;'
```

Here is the file it writes out:
```
### NRDP Check ###
start_time=1560978379
# Time: Wed, 19 Jun 2019 16:06:19 -0500
host_name=localhost
service_description=PING
check_type=1
early_timeout=1
exited_ok=1
return_code=2
output=OK: result1=1; result2=2;\n
```
