### ISSUE TITLE
Data not proccessing

### ISSUE THREAD

**Issue by laramy2020** [NagiosEnterprises/nrdp#46]
Server Centos 7.7
Nagios core 4.4.3 (epel repo install)
nrdp 2.0.2
Client Centos 7.7
nsca 2.2.0

Passive commands send
![image](https://user-images.githubusercontent.com/1227781/69275161-18ab4200-0b99-11ea-9869-26d3a0fee926.png)
Passive commands show up in the checkresults folder
![image](https://user-images.githubusercontent.com/1227781/69275233-3f697880-0b99-11ea-8905-36d9f80d690c.png)
Passive commands proccess (the folder automaticly empties)

Nothing showes up in nagios.log about the data being proccessed

Passive checks are enabled
Nagcmd has both apache and nagios users assigned to it
Selinux is disabled

**Comment by box293** [comment]
I'm not 100% clear what you mean by "Data not processing".

> Nothing showes up in nagios.log about the data being proccessed

Do the host and service objects exist in Nagios? If they do then no logging occurs by default on known objects.

You may want to enable logging `log_passive_checks=1` as per https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/configmain.html

**Comment by laramy2020** [comment]
Ok sorry, forgot to mention
Yes it is defined, the hosts/services are still grey and pending
When running a test at ip/nrdp i still see nothing in nagios.log
I will give your logging config a test.

**Comment by laramy2020** [comment]
That is already set as 1 in my config
so is accepting host and service passive checks.

**Comment by box293** [comment]
Try setting the debug level on and then restart Nagios.

```
sed -i 's/.*debug_level=.*/debug_level=-1/g' /usr/local/nagios/etc/nagios.cfg
service nagios restart
```

Then watch the file /usr/local/nagios/var/nagios.debug

When you are finished this turns debugging off:

```
sed -i 's/.*debug_level=.*/debug_level=0/g' /usr/local/nagios/etc/nagios.cfg
service nagios restart
```

**Comment by Bangaio65** [comment]
Check that you have the group sticky bit set:
`chmod g+s ~nagios/checkresults/`

**Comment by derekschrock** [comment]
It seems this could go two ways... install `php-process` to get the posix function to allow the chgrp or have the EPEL package g+s checkresults/.

**Comment by Joan31** [comment]
Hi,
Same trouble here. NRDP does not work fine.

I installed php-process and changed chmod g+s /.../checkresults/

When I try to execute a request with a nrdp client (send_nrdp.sh), files appear inside ../checmkresults/ and disappear after few seconds.

But, in Nagios, the service does not change.

Nothing appear on logs.... (debug level 1 and log passive check are enabled).

**Comment by darrick** [comment]
I had this same problem when trying to use it via a docker container based on alpine.  Installing php7-posix fixed it.  

I got the misleading error message: "nagios_command_group=nagios does not exist, not chgrp()ing". Which doesn't mean the group doesn't exist.  It means the posix_getgrnam function does not exist.

Passive commands would show up in the checkresults folder and sticky bit was set.  And then then commands would randomly disappear.
