### ISSUE TITLE
$cfg["tmp_dir"] not used anywhere

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nrdp#5]
Reported by Janice Singh:

https://support.nagios.com/forum/viewtopic.php?f=34&t=34714&p=152815#p152815

From the post:

"`$cfg["tmp_dir"]` is not used anywhere. It is trying to write to `$cfg["check_results_dir"]`."

I vaguely recall running into this same issue when working on nagduino.

**Comment by jomann09** [comment]
Pretty sure I will just merge the removal of this in but keeping this open for now because I am unsure whether there was a reason behind adding it and if we should actually be using it somewhere... I doubt we need to though.

**Comment by jomann09** [comment]
Merging in #12 so closing this
