### ISSUE TITLE
send_nrdp.php produces handle_api_error(msg=BAD XML)

### ISSUE THREAD

**Issue by ccztux** [NagiosEnterprises/nrdp#52]
```send_nrdp.php``` uses wrong method for converting strings to html entities. Depending on the chars in the plugin output this can result in an invalid xml and produces the following error: ```handle_api_error(msg=BAD XML)``` on the NRDP server.
I will provide a fix via a pull request.

**Comment by ccztux** [comment]
Tested, works.

Reference:
[htmlentities() vs htmlspecialchars() for a valid XML with PHP](https://thicolares.com/2019/04/30/htmlentities-vs-htmlspecialchars-for-a-valid-xml-with-php.html)

**Comment by jomann09** [comment]
Closing issue due to merge.
