### ISSUE TITLE
Support JSON in addition to XML

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nrdp#7]
With Logserver using JSON, and the XI 5 API doing the same, it makes sense for NRDP to follow suit.  Besides, JSON is much nicer to work with that XML anyway.

**Comment by hedenface** [comment]
It would be nice to cover this at the next internal OSS meeting.

**Comment by hedenface** [comment]
Added in https://github.com/NagiosEnterprises/nrdp/commit/ca9638bd30b485219290da8c59f0b68ad499852d from PR #23
